// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NumbersRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumbersRequest) Reset()         { *m = NumbersRequest{} }
func (m *NumbersRequest) String() string { return proto.CompactTextString(m) }
func (*NumbersRequest) ProtoMessage()    {}
func (*NumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{0}
}

func (m *NumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumbersRequest.Unmarshal(m, b)
}
func (m *NumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumbersRequest.Marshal(b, m, deterministic)
}
func (m *NumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumbersRequest.Merge(m, src)
}
func (m *NumbersRequest) XXX_Size() int {
	return xxx_messageInfo_NumbersRequest.Size(m)
}
func (m *NumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NumbersRequest proto.InternalMessageInfo

func (m *NumbersRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *NumbersRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type AnswerReply struct {
	Ans                  int32    `protobuf:"varint,1,opt,name=ans,proto3" json:"ans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerReply) Reset()         { *m = AnswerReply{} }
func (m *AnswerReply) String() string { return proto.CompactTextString(m) }
func (*AnswerReply) ProtoMessage()    {}
func (*AnswerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{1}
}

func (m *AnswerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerReply.Unmarshal(m, b)
}
func (m *AnswerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerReply.Marshal(b, m, deterministic)
}
func (m *AnswerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerReply.Merge(m, src)
}
func (m *AnswerReply) XXX_Size() int {
	return xxx_messageInfo_AnswerReply.Size(m)
}
func (m *AnswerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerReply.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerReply proto.InternalMessageInfo

func (m *AnswerReply) GetAns() int32 {
	if m != nil {
		return m.Ans
	}
	return 0
}

func init() {
	proto.RegisterType((*NumbersRequest)(nil), "main.NumbersRequest")
	proto.RegisterType((*AnswerReply)(nil), "main.AnswerReply")
}

func init() { proto.RegisterFile("math.proto", fileDescriptor_f139a3799a86a974) }

var fileDescriptor_f139a3799a86a974 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe1, 0xe2,
	0xf3, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x2a, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2,
	0xe1, 0x62, 0x4c, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0x4c, 0x04, 0xf1, 0x92, 0x24,
	0x98, 0x20, 0xbc, 0x24, 0x25, 0x79, 0x2e, 0x6e, 0xc7, 0xbc, 0xe2, 0xf2, 0xd4, 0xa2, 0xa0, 0xd4,
	0x82, 0x9c, 0x4a, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xbc, 0x62, 0xa8, 0x62, 0x10, 0xd3, 0xc8, 0x91,
	0x8b, 0xd7, 0xb7, 0xd2, 0x37, 0xb1, 0x24, 0x23, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x80, 0x8b, 0xd9, 0x31, 0x25, 0x45, 0x48, 0x44, 0x0f, 0x64, 0x9b, 0x1e, 0xaa, 0x55, 0x52, 0x82,
	0x10, 0x51, 0x24, 0x23, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xce, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0xeb, 0xb6, 0xb9, 0xac, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyMathServiceClient is the client API for MyMathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyMathServiceClient interface {
	Add(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*AnswerReply, error)
}

type myMathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyMathServiceClient(cc *grpc.ClientConn) MyMathServiceClient {
	return &myMathServiceClient{cc}
}

func (c *myMathServiceClient) Add(ctx context.Context, in *NumbersRequest, opts ...grpc.CallOption) (*AnswerReply, error) {
	out := new(AnswerReply)
	err := c.cc.Invoke(ctx, "/main.MyMathService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyMathServiceServer is the server API for MyMathService service.
type MyMathServiceServer interface {
	Add(context.Context, *NumbersRequest) (*AnswerReply, error)
}

// UnimplementedMyMathServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMyMathServiceServer struct {
}

func (*UnimplementedMyMathServiceServer) Add(ctx context.Context, req *NumbersRequest) (*AnswerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterMyMathServiceServer(s *grpc.Server, srv MyMathServiceServer) {
	s.RegisterService(&_MyMathService_serviceDesc, srv)
}

func _MyMathService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyMathServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.MyMathService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyMathServiceServer).Add(ctx, req.(*NumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyMathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.MyMathService",
	HandlerType: (*MyMathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MyMathService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}
